
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME_TEST'] %>


production:
  pool: 5
  port: 5432
  database: dfbvjc5r2p26vr
  username: yimqtnrblvjtld
  password: <%= ENV['8db0f402f48bb00f71e6b28996a6e89ce3ec08dffb7897563372ae85e6afa193'] %>
